### ISSUE TITLE
How to proceed

### ISSUE THREAD

**Issue by NeuCp** [vorou/kdiff3-solarized-dark#1]
Hi Vorou,
Could you please indicate how to proceed with your kdiff3rc file to configure the solarized dark in kdiff3?
Thanks!!

**Comment by vorou** [comment]
Hey, don't have kdiff3 installed at the moment, but I guess you could just overwrite your .kdiff3rc (should probably be in your ~/ folder) with this one.

Keep in mind that it'll overwrite any other changes you've done.
